canonical: https://interop.esante.gouv.fr/ig/fhir/mos
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: interop.esante.gouv.ig.fhir.mos
name: InteropEsanteGouvIgFhirMos
status: draft
